import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-3">
          <nav>
            <h1 className="text-3xl font-bold text-center">Getting Mail to Notion LabelFilter</h1>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
